// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Author = Collections['authors']['schema']['_output']
export declare const authors: Author[]

export type Page = Collections['pages']['schema']['_output']
export declare const pages: Page[]

export type TIL = Collections['tils']['schema']['_output']
export declare const tils: TIL[]

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]

export type Design = Collections['designs']['schema']['_output']
export declare const designs: Design[]
