import type { Site } from "@/types";

export const siteConfig: Site = {
  name: "azekowka.me",
  title: "Aziz Gabitov | Software Engineer",
  description: "Hi, I'm Aziz - Got ideas you are itching to bring to life? Let's collaborate and make it happen!",
  keywords: [
    "aziz gabitov",
    "azekowka",
    "azekowka portfolio",
    "azekowka website",
    "azekowka 2024",
    "azekowka 2024 website",
    "azekowka 2024 portfolio",
    "azekowka 2024 portfolio website",
    "azekowka 2024 portfolio website 2024",
    "azekowka 2024 portfolio website 2025",
    "azekowka 2024 portfolio 2025",
    "azekowka 2024 portfolio 2025 website",
    "azekowka 2024 portfolio 2025 website 2025",
    "portfolio",
    "aziz portfolio",
    "aziz 100x dev",
    "full stack developer",
    "designer",
    "web developer",
    "web designer",
    "react developer",
    "react designer",
    "next.js developer",
    "next.js designer",
    "abdulaziz gabitov portfolio",
    "abdulaziz gabitov website",
    "abdulaziz gabitov portfolio website",
    "abdulaziz gabitov portfolio website 2025",
    "abdulaziz gabitov portfolio 2025",
    "Abdulaziz Gabitov",
    "azekowka",
    "azekowka me",
    "azekowka.me", 
  ],
  siteUrl: "https://azekowka.me",
  creator: {
    name: "Aziz Gabitov",
    url: "https://azekowka.me",
  },
  ogImage: "https://azekowka.me/meta_thumb.png",
  links: {
    x: "https://x.com/azekowka",
    github: "https://github.com/azekowka",
  }
}