export const skillsConfig = [
  {
    category: "Frontend",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "TailwindCSS",
      "SCSS",
      "HTML/CSS",
      "Prettier",
      "Headless UI",
      "shadcn/ui",
      "Framer motion",
      "GSAP",
      "Redux",
      "Recoil",
      "Zod",
      "Zustand",
      "Knip",
      "Tanstack Query",
      "Tanstack Router",
      "React Hook Form",
    ],
  },
  {
    category: "Backend",
    technologies: [
      "Express.js",
      "FastAPI",
      "Flask",
      "Go",
      "tRPC/gRPC",
      "Prisma",
      "Drizzle ORM",
    ],
  },
  {
    category: "Database",
    technologies: [
      "AWS S3",
      "Supabase",
      "NeonDB",
      "InstantDB",
      "MySQL",
      "MongoDB",
      "DynamoDB",
      "PostgreSQL",
      "Redis",
      "Celery"
    ],
  },
  {
    category: "Cloud & DevOps",
    technologies: [
      "AWS Certified",
      "Azure Certified",
      "Vercel",
      "Railway",
      "Render",
      "Supabase",
      "Cloudflare",
      "Firebase",
    ],
  },
  {
    category: "JavaScript runtime",
    technologies: [
      "Node.js",
      "Bun",
      "Deno"
    ],
  },
  {
    category: "Artificial Intelligence",
    technologies: ["LangChain", "LangSmith", 
      "Google AI Studio", "Azure AI Foundry", 
      "OpenAI Whisper", 
      "OpenRouter", "Groq AI Inference",
      "HeyGen", "Together AI", "Ollama"],
  },
    {
    category: "Developer Tools",
    technologies: ["Git", "21st.dev", 
      "v0", "Polar Payments (Stripe)", 
      "ClerkAuth", "BetterAuth", 
      "SingleStore", "Uploadthing",
      "Namecheap", "Name.com", "Figma",
      "Postman", "VS Code", "Trae", "Cursor"],
  },
];
